### ISSUE TITLE
java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by Patil-Kranti** [KePeng1019/SmartPaperScan#3]
E/SurfaceView: Exception configuring surface
               java.lang.RuntimeException: setParameters failed
                   at android.hardware.Camera.native_setParameters(Native Method)
                   at android.hardware.Camera.setParameters(Camera.java:2102)
                   at com.pengke.paper.scanner.scan.ScanPresenter.initCamera(ScanPresenter.kt:124)
                   at com.pengke.paper.scanner.scan.ScanPresenter.surfaceCreated(ScanPresenter.kt:129)
                   at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
                   at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
                   at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
                   at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                   at android.view.Choreographer.doFrame(Choreographer.java:696)
                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                   at android.os.Handler.handleCallback(Handler.java:873)
                   at android.os.Handler.dispatchMessage(Handler.java:99)
                   at android.os.Looper.loop(Looper.java:193)
                   at android.app.ActivityThread.main(ActivityThread.java:6669)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by KePeng1019** [comment]
it seems I set wrong configuration for some device, I just update the preview and picture  size configuration, this maybe help. can you please pull the newest code and have a try? thank you

**Comment by Patil-Kranti** [comment]
I did clone latest repository but error is still there.
can you help?
thanks..

**Comment by KePeng1019** [comment]
so what is your device resolution? error is caused by i set wrong camera resolution configuration, or may be you can just try another device see what is happening.

**Comment by Patil-Kranti** [comment]
My resolution is 1920x1080
I tried 640x480 and 720x960 but the error still persist

**Comment by KePeng1019** [comment]
i am wondering if you are using a virtual device? this project is not work on virtual device, so if you are using a virtual device, you should replace with a real one

**Comment by Patil-Kranti** [comment]
yes i was tring it on android emulator i'll check on my phone

**Comment by Patil-Kranti** [comment]
it worked thanks 
but I am not able to find the scanned images can you give the location where you save the images

**Comment by KePeng1019** [comment]
there are several images on detecting rectangle process including origin image, cropped image and enhanceed image, i do not save it to disks due to i donot know which one you want. i think you can change the code and save it disk on your need or it's my pleasure to help you save these picture to disks on your need. so if you need my help to do this, you can tell me which picture you want to save to disk.

**Comment by KePeng1019** [comment]
sorry for my poor English~~

**Comment by Patil-Kranti** [comment]
I don't how to code in kotlin if you could tell me how to save the enhanced image to the disk.
it would be of great help.
and also the menu option is not displaying in the app.

**Comment by KePeng1019** [comment]
ok, when i finished, i will tell you.

**Comment by KePeng1019** [comment]
> I don't how to code in kotlin if you could tell me how to save the enhanced image to the disk.
> it would be of great help.
> and also the menu option is not displaying in the app.

I add a menu to save picture, so you can save the picture to your disk. path is: /storage/emulated/0/smart_scanner
you can update and have a try.

**Comment by Patil-Kranti** [comment]
thanks for the help but the auto cropping is not working now

**Comment by KePeng1019** [comment]
> thanks for the help but the auto cropping is not working now
uh, it not auto cropping, it just makr the picture largest rectangle, you should crop it by click the crop button then crop the rectangle including part.

**Comment by Patil-Kranti** [comment]
yes that's what I am saying that it is not detecting the paper

**Comment by KePeng1019** [comment]
> yes that's what I am saying that it is not detecting the paper

ok, it not work for every paper. May be algorithm can not detect the rectangle of the preview frame or the picture you take, so it not always works. I do not change the algorithm, so maybe it just can not work for the paper you puton

**Comment by Patil-Kranti** [comment]
hi
can you tell me how to add activity to view scanned images
